/* ══════════════════════════════════════════════════════
   UltraDev SideCart — CSS
   Compatible with the HTML generated by sidecart.js
   ══════════════════════════════════════════════════════ */

:root {
    --usc-bg:      #ffffff;
    --usc-border:  #e8e8e8;
    --usc-text:    #202223;
    --usc-muted:   #8a8a8a;
    --usc-danger:  #e8312a;
    --usc-accent:  #2c85c8;
    --usc-radius:  5px;
    --usc-speed:   0.2s;
    --usc-width:   400px;
}

/* ── Overlay ─────────────────────────────────────────── */
#usc-overlay {
    display: none;
    position: fixed;
    inset: 0;
    background: rgba(0,0,0,0.45);
    z-index: 9998;
}
body.usc-open #usc-overlay { display: block; }

/* ── Panel ──────────────────────────────────────────── */
#usc-panel {
    position: fixed;
    top: 0;
    right: -420px;
    width: var(--usc-width);
    max-width: 100vw;
    height: 100%;
    background: var(--usc-bg);
    z-index: 9999;
    display: flex;
    flex-direction: column;
    box-shadow: -4px 0 24px rgba(0,0,0,0.12);
    transition: right var(--usc-speed) ease;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
    font-size: 14px;
    color: var(--usc-text);
}
body.usc-open #usc-panel { right: 0; }

#usc-panel-inner {
    height: 100%;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

/* ── Cart container ──────────────────────────────────── */
.usc-cart {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
}

/* ── Header ──────────────────────────────────────────── */
.usc-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 !important;
    background: #fbfbfb;
    border-bottom: none;
    flex-shrink: 0;
}
.usc-title {
    font-size: 16px;
    font-weight: 400;
    letter-spacing: 0.05em;
    text-transform: uppercase;
}
.usc-title strong { font-weight: 700; }

.usc-close {
    background: #f0f0f0 !important;
    padding: 16px 20px !important;
    border: none;
    cursor: pointer;
    color: var(--usc-text);
    font-size: 18px;
    border-radius: 0;
}
.usc-edit {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--usc-text);
    font-size: 18px;
    padding: 4px;
    line-height: 1;
    border-radius: 4px;
    transition: opacity var(--usc-speed);
}
.usc-close:hover, .usc-edit:hover { opacity: 0.6; }

/* ── Items (scroll) ──────────────────────────────────── */
.usc-items {
    flex: 1;
    overflow-y: auto;
    padding: 0 8px;
}

.usc-table {
    width: 100%;
    border-collapse: collapse;
}

.usc-row {
    border-bottom: none;
}
.usc-row:last-child { border-bottom: none; }

.usc-thumb {
    width: 85px;
    padding: 14px 10px 14px 12px;
    vertical-align: top;
}
.usc-thumb img {
    width: 75px;
    height: 75px;
    object-fit: cover;
    border-radius: var(--usc-radius);
    border: 1px solid #dcdcdc !important; /* Defined and complete color */
    display: block;
    box-shadow: none !important; /* Ensures no shadow */
}

.usc-details {
    padding: 14px 4px 14px 0;
    vertical-align: top;
}
.usc-name {
    font-size: 13px;
    font-weight: 400;
    line-height: 1.4;
    margin-bottom: 4px;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
}
.usc-name a { color: var(--usc-text); text-decoration: none !important; }
.usc-name a:hover { text-decoration: none !important; color: var(--usc-accent); }

.usc-options {
    font-size: 11px;
    color: var(--usc-muted);
    margin-bottom: 6px;
}
.usc-price {
    font-size: 14px;
    color: var(--usc-text);
    margin-top: 4px;
}

.usc-actions {
    width: 90px;
    padding: 14px 12px 14px 4px;
    vertical-align: top;
    text-align: right;
}
.usc-remove {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--usc-muted);
    font-size: 15px;
    padding: 2px 4px;
    margin-bottom: 10px;
    display: block;
    margin-left: auto;
    border-radius: 4px;
    transition: color var(--usc-speed);
}
.usc-remove:hover { color: var(--usc-danger); }

/* Qty wrap */
.usc-qty-wrap {
    display: inline-flex;
    align-items: center;
    border: 1px solid #ddd;
    border-radius: 5px;
    margin-top:14px;
    overflow: hidden;
    height: 30px;
    background: #fff;
}
.usc-qty-btn {
    width: 28px;
    height: 30px;
    border: none;
    background: transparent;
    cursor: pointer;
    font-size: 16px;
    line-height: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--usc-text);
    transition: background var(--usc-speed);
    flex-shrink: 0;
}
.usc-qty-btn:hover { background: #f4f4f4; }
.usc-qty-btn:disabled { opacity: 0.4; cursor: not-allowed; }

.usc-qty {
    width: 30px;
    height: 30px;
    border: none;
    border-left: 1px solid #d0d0d0;
    border-right: 1px solid #d0d0d0;
    text-align: center;
    font-size: 13px;
    font-weight: 600;
    background: #fff;
    color: var(--usc-text);
}
.usc-qty::-webkit-inner-spin-button,
.usc-qty::-webkit-outer-spin-button { -webkit-appearance: none; }

/* ── Empty state ─────────────────────────────────────── */
.usc-cart--empty { 
    justify-content: center; 
    height: 100%; 
}

.usc-empty-msg {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;    /* Centers horizontally */
    justify-content: center; /* Centers vertically */
    padding: 40px 24px;
    text-align: center;
    color: var(--usc-muted);
}
.usc-empty-msg p { 
    margin-bottom: 20px; 
    font-size: 15px; 
}


/* ── Footer ──────────────────────────────────────────── */
.usc-footer {
    border-top: none;
    padding: 16px 20px;
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    gap: 10px;
}

/* Totals */
.usc-totals { display: flex; flex-direction: column; gap: 8px; background: #f8f8f8; padding: 15px; border-radius: 5px; margin-bottom: 10px; }
.usc-total-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 14px;
}

/* REQUESTED WEIGHT LOGIC:
   1. Default total (no coupon) = 700
   2. Subtotal (when coupon applied) = 400
   3. Final Value = 700
*/
.usc-total-row span { font-weight: 700; } /* Default (Total) */

.usc-total-row.usc-is-subtotal span { font-weight: 400; } /* Removes weight if it is subtotal */

.usc-discount-row { color: #2a8a2a; font-size: 14px; }
.usc-discount-row span { font-weight: 400; }

.usc-total-row.usc-is-final { 
    font-size: 15px; 
    border-top: none; 
    padding-top: 8px; 
    margin-top: 4px; 
}
.usc-total-row.usc-is-final span { font-weight: 700; }

/* Coupon */
.usc-coupon-input-wrap,
.usc-coupon-applied {
    display: flex;
    align-items: stretch;
    border: 1px solid var(--usc-border);
    border-radius: var(--usc-radius);
    overflow: hidden;
    height: 38px;
}
.usc-coupon-input {
    flex: 1;
    padding: 0 12px;
    border: none !important;
    font-size: 13px;
    outline: none;
    background: transparent;
}
.usc-coupon-apply,
.usc-coupon-remove {
    padding: 0 16px;
    border: none;
    border-left: 1px solid var(--usc-border);
    background: #f9f9f9;
    cursor: pointer;
    font-size: 12px;
    font-weight: 400;
    transition: all var(--usc-speed);
}
.usc-coupon-apply:hover {
    background: #2c85c8 !important;
    color: #fff;
}
.usc-coupon-remove:hover {
    background: #b73741 !important;
    color: #fff;
}
.usc-coupon-msg { font-size: 12px; margin-top: 4px; min-height: 16px; }
.usc-msg--error  { color: var(--usc-danger); }
.usc-msg--success { color: #2a8a2a; }

/* Action buttons */
.usc-btn-checkout {
    display: block;
    width: 100%;
    height:55px;
    padding: 13px;
    background: var(--usc-accent);
    color: #fff;
    border: none;
    border-radius: var(--usc-radius);
    font-size: 14px;
    font-weight: 400;
    cursor: pointer;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    transition: opacity var(--usc-speed);
}
.usc-btn-checkout:hover { background-color: #28A745; opacity: 1; }

.usc-btn-continue {
    display: block;
    width: 100%;
    padding: 10px;
    background: transparent;
    color: var(--usc-muted);
    border: none;
    font-size: 11px;
    font-weight: 700;
    cursor: pointer;
    text-decoration: none !important;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    transition: color var(--usc-speed);
}
.usc-btn-continue:hover {
    color: #2c85c8 !important;
    text-decoration: none !important;
}
.usc-btn-continue:hover { color: var(--usc-text); }

/* ── Counter badge in header ────────────────────────── */
.mini-cart-heading { position: relative; }
.usc-badge.count {
    position: absolute;
    top: 3.5px;
    right: 6px;
    display: inline-block;
    width: 18px;
    height: 18px;
    line-height: 18px;
    text-align: center;
    font-size: 10px;
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
    background-color: var(--usc-danger);
    color: #fff;
    border-radius: 50%;
    z-index: 10;
}

/* ── Responsive ──────────────────────────────────────── */
@media (max-width: 480px) {
    #usc-panel { width: 100vw; }
    .usc-thumb { width: 70px; padding: 10px 8px 10px 10px; }
.usc-thumb img {
    width: 75px;
    height: 75px;
    object-fit: cover;
    border-radius: var(--usc-radius);
    border: 1px solid #dcdcdc !important; /* Defined and complete color */
    display: block;
    box-shadow: none !important; /* Ensures no shadow */
}
}
